Updating Dockerfile

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,12 +1,25 @@
 name: "Docker"
-# build and publish manylinux_2_34_x86_64 with GraalVM, Maven and Poetry
+# build and publish different docker images
 on:
+  release:
+    types:
+      - published
   workflow_dispatch:
     inputs:
+      target:
+        description: 'Select which dockerfile to build (note: "manylinux" times out currently)'
+        required: true
+        options:
+          - main
+          - manylinux
       tag:
         description: "Tag for the Docker image"
         required: true
         default: "latest"
+      push:
+        description: "Push docker image to container registry once built?"
+        required: true
+        default: "false"
 
 
 jobs:
@@ -23,6 +36,8 @@ jobs:
     steps:
       - name: Check out
         uses: actions/checkout@v4
+        with:
+          submodules: true
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -37,10 +52,30 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
+      - name: Determine docker image source
+        shell: bash
+        run: |
+          if [[ "${{ github.event.inputs.target }}" == "main" ]]; then
+            echo "DOCKERFILE_PATH=Dockerfile" >> $GITHUB_ENV
+            echo "DOCKER_REPO_TAG=ghcr.io/virtualcell/vcell_fvsolver_${{ matrix.platform.arch }}:${{ github.event.inputs.tag }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event.inputs.target }}" == "manylinux" ]]; then
+            echo "DOCKERFILE_PATH=docker/Dockerfile_fvsolver_manylinux_2_34_${{ matrix.platform.arch }}" >> $GITHUB_ENV
+            echo "DOCKER_REPO_TAG=ghcr.io/virtualcell/fvsolver_manylinux_2_34_${{ matrix.platform.arch }}:${{ github.event.inputs.tag }}" >> $GITHUB_ENV
+          else
+            echo "Error: Unknown target requested" >&2
+            exit 1
+          fi
+
       - name: Build and push
         uses: docker/build-push-action@v6
         with:
-          context: docker
-          file: docker/Dockerfile_fvsolver_manylinux_2_34_${{ matrix.platform.arch }}
-          push: true
-          tags: ghcr.io/virtualcell/fvsolver_manylinux_2_34_${{ matrix.platform.arch }}:${{ github.event.inputs.tag }}
+          context: .
+          file: ${{ env.DOCKERFILE_PATH }}
+          push: ${{ github.event.inputs.push || github.event_name == 'release' }}
+          tags: ${{ env.DOCKER_REPO_TAG }}
+
+      - name: Setup Debug-shell Session on Failure
+        uses: mxschmitt/action-tmate@v3
+        if: ${{ failure() }}
+        with:
+          limit-access-to-actor: true
